# PHP artisan
if [ -f ~/.dotfiles/shell/aliases/artisan ]; then
    . ~/.dotfiles/shell/aliases/artisan
fi

# PHP composer
if [ -f ~/.dotfiles/shell/aliases/composer ]; then
    . ~/.dotfiles/shell/aliases/composer
fi

# Git
if [ -f ~/.dotfiles/shell/aliases/git ]; then
    . ~/.dotfiles/shell/aliases/git
fi

# MySQL
if [ -f ~/.dotfiles/shell/aliases/mysql ]; then
    . ~/.dotfiles/shell/aliases/mysql
fi

# SSH
if [ -f ~/.dotfiles/shell/aliases/ssh ]; then
    . ~/.dotfiles/shell/aliases/ssh
fi

# IDE
if [ -f ~/.dotfiles/shell/aliases/ide ]; then
    . ~/.dotfiles/shell/aliases/ide
fi

# MacOS
if [ -f ~/.dotfiles/shell/aliases/makeos ]; then
    . ~/.dotfiles/shell/aliases/makeos
fi
