#!/bin/sh

# Function definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_functions, instead of adding them here directly.
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# some more ls aliases
alias l="ls -Glh"
alias ll="ls -Glh"
alias la="ls -Galh"
alias ls="ls -G"

# Custom terminal colors
export LSCOLORS=GxfxcxdxBxegedabagaced

# PS1 variable format
export PS1="\h:➜ \[\033[1;36m\]\W\[\033[32m\]\$(git_prompt_info)\[\033[0m\] "

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export HOMEBREW_NO_AUTO_UPDATE=1
export BASH_SILENCE_DEPRECATION_WARNING=1

export PATH="/Library/Developer/CommandLineTools/usr/bin:$PATH"
export PATH="/usr/local/anaconda3/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="~/.composer/vendor/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
